require('components/zonecontrol/blink')
require('components/zonecontrol/zones')
require('components/zonecontrol/cleaner')
require('components/zonecontrol/map')
-- require('components/zonecontrol/test')
