
-- component list. comment out things to disable them
require('components/filters/index')
require('components/abilities/index')
require('components/reflexfilters/index')
require('components/creeps/index')
require('components/points/index')
require('components/gold/index')
require('components/zonecontrol/index')
require('components/duels/index')
require('components/boss/index')
require('components/progression/index')
require('components/courier/index')
require('components/cave/index') -- must be after creeps
require('components/doors/index')
require('components/glyph/index')
require('components/devcheats/index')
require('components/player/index')
require('components/statprovider/index')
require('components/heroselection/index')
require('components/music/index')
require('components/debug_overlay/index')
