
-- component list. comment out things to disable them
require('components/filters/index')
require('components/abilities/index')
require('components/reflexfilters/index')
require('components/minimap/index')
require('components/creeps/index')
require('components/points/index')
require('components/gold/index')
require('components/experience/index')
require('components/zonecontrol/index')
require('components/duels/index')
require('components/surrender/index')
require('components/boss/index')
require('components/progression/index')
require('components/courier/index')
require('components/startingitems/index')
require('components/cave/index') -- must be after creeps
require('components/doors/index')
require('components/glyph/index')
require('components/devcheats/index')
require('components/player/index')
require('components/capturepoints/index')
require('components/statprovider/index')
require('components/heroselection/index')
require('components/music/index')
require('components/items/index')
require('components/bottlepass/index')
require('components/team_select/index')
require('components/runes/index')
require('components/sparks/index')

-- should be last
require('components/saveload/index')
